### ISSUE TITLE
An error occurred while trying to extract seraphine's SFX file.

### ISSUE THREAD

**Issue by Virace** [Morilli/bnk-extract#1]
> Assertion failed: fread(new_music_container_object.music_track_ids, 4, new_music_container_object.music_track_id_amount, bnk_file) == new_music_container_object.music_track_id_amount, file sound.c, line 247

assets/sounds/wwise2016/sfx/characters/seraphine/skins/skin01/seraphine_skin01_sfx_events.bnk
assets/sounds/wwise2016/sfx/characters/seraphine/skins/skin01/seraphine_skin01_sfx_audio.bnk
data/characters/seraphine/skins/skin0.bin

**Comment by Morilli** [comment]
Yeah i actually know of that issue and have tried to "fix" it by just skipping this specific case that fails, but then I don't get any connections for this bnk file. I was trying to think of whether I could actually make it work correctly and didn't wanna push the fix. 

For now it's probably best to do that though in order to prevent random issues like this coming up in the future (will do that once I'm home™️).

If you want a quick-fix extracting without events should work.

**Comment by Virace** [comment]
[http://wiki.xentax.com/index.php/Wwise_SoundBank_(*.bnk)#type_.2313:_Music_Playlist_Container](http://wiki.xentax.com/index.php/Wwise_SoundBank_(*.bnk)#type_.2313:_Music_Playlist_Container)
I have also tried to fix this problem by following the format in this website. 
This is the only one that I can refer to. 
but, not work.

**Comment by Morilli** [comment]
Yeah I have also been following the site for reference but have found numerous inconsistencies, so I can't directly implement everything that is documented there.

**Comment by Morilli** [comment]
@Virace can you try https://github.com/Morilli/bnk-extract/releases/tag/v1.4? I should have fixed all issues with parsing the music container in that release.

Please report back if you can see this same issue happening again.

**Comment by Virace** [comment]
Yes, for 1.4, no more errors, and also no more events
